CREATE TABLE PIZZA_SALES
	(
	PIZZA_ID INTEGER PRIMARY KEY,
	ORDER_ID INTEGER,
	PIZZA_NAME_ID TEXT,
	QUANTITY INTEGER,
	ORDER_DATE DATE,
	ORDER_TIME TIME,
	UNIT_PRICE NUMERIC(10,2),
	TOTAL_PRICE NUMERIC(10,2),
	PIZZA_SIZE VARCHAR(10),
	PIZZA_CATAGORY VARCHAR(10),
	PIZZA_INGREDENTS TEXT,
	PIZZA_NAME TEXT
	);
SELECT * FROM PIZZA_SALES;

-- KPI

-- 1. TOTAL REVENUE

SELECT SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM PIZZA_SALES;

-- 2.TOTAL ORDERS

SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER FROM PIZZA_SALES;

-- 3. AVERAGE ORDER VALUE 
SELECT CAST(CAST(SUM(TOTAL_PRICE) AS DECIMAL (10,2))/
CAST(COUNT(DISTINCT ORDER_ID) AS DECIMAL(10,2)) AS DECIMAL (10,2))
AS AVG_ORDER_VALUE 
FROM PIZZA_SALES;

-- 4.TOTAL PIZZA SOLD

SELECT SUM(QUANTITY) AS TOTAL_PIZZA_SOLD FROM PIZZA_SALES;

-- 5. AVERAGE PIZZA PER ORDER 

SELECT CAST(CAST(SUM(QUANTITY) AS DECIMAL (10,2))/
CAST(COUNT(DISTINCT ORDER_ID)AS DECIMAL (10,2))
AS DECIMAL (10,2))AS AVG_PIZZA_PER_ORDER
FROM PIZZA_SALES;

SELECT * FROM PIZZA_SALES;

-- ANALYSIS
-- 1. MONTLY TREND FOR TOTAL REVENUE 

SELECT TO_CHAR( Order_date, 'DAY') AS order_day,
COUNT(DISTINCT order_id) AS total_orders 
FROM pizza_sales
GROUP BY TO_CHAR( Order_date, 'DAY');

-- 2. Monthly Trend for Orders
SELECT TO_CHAR( Order_date, 'MONTH') AS order_day, 
COUNT(DISTINCT order_id) AS total_orders 
FROM pizza_sales
GROUP BY TO_CHAR( Order_date, 'MONTH');

-- 3. % of Sales by Pizza Category.
SELECT pizza_catagory, 
CAST(SUM(total_price) AS DECIMAL(10,2)) as total_revenue,
CAST(SUM(total_price) * 100 / (SELECT SUM(total_price) from pizza_sales) AS DECIMAL(10,2)) AS PCT
FROM pizza_sales
GROUP BY pizza_catagory;

-- 4. % of Sales by Pizza Size.

SELECT pizza_size, 
CAST(SUM(total_price) AS DECIMAL(10,2)) as total_revenue,
CAST(SUM(total_price) * 100 / (SELECT SUM(total_price) from pizza_sales) AS DECIMAL(10,2)) AS PCT
FROM pizza_sales
GROUP BY pizza_size;

-- 5. total pizza sold by pizza size and catagory
select pizza_size, sum(Quantity) as total_pizza_size
from pizza_sales
GROUP BY pizza_size;

select pizza_catagory, sum(Quantity) as total_pizza_sold
from pizza_sales
GROUP BY pizza_catagory;


UPDATE PIZZA_SALES
SET TEMP_NAME=PIZZA_NAME;

SELECT * FROM PIZZA_SALES;
UPDATE PIZZA_SALES
SET PIZZA_NAME = PIZZA_INGREDENTS;

UPDATE PIZZA_SALES
SET PIZZA_INGREDENTS =PIZZA_NAME;

UPDATE PIZZA_SALES
SET PIZZA_INGREDENTS = TEMP_NAME;

ALTER TABLE PIZZA_SALES
DROP COLUMN TEMP_NAME;


-- 6. REVENUE BY PIZZA NAME 
SELECT pizza_name, SUM(total_price) AS Total_Revenue
FROM pizza_sales
GROUP BY PIZZA_NAME
ORDER BY TOTAL_REVENUE ASC
LIMIT 5;

SELECT * FROM PIZZA_SALES;

-- top & bottom analysis

-- 1. Top PIZZA BY REVENUE 

SELECT pizza_name, SUM(total_price) AS Total_Revenue
FROM pizza_sales
GROUP BY PIZZA_NAME
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;

-- 2. BOTTOM PIZZA BY REVENUE 

SELECT PIZZA_NAME, SUM(TOTAL_PRICE) AS TOTAL_REVENUE
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_REVENUE
LIMIT 5;

-- 3. TOP PIZZA BY ORDER

SELECT PIZZA_NAME, SUM(ORDER_ID) AS TOTAL_ORDER
FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_ORDER DESC
LIMIT 5;

-- 4. WORST PIZZA BY ORDER 

SELECT PIZZA_NAME, SUM(ORDER_ID) AS TOTAL_ORDER
FROM PIZZA_SALES
GROUP BY PIZZA_NAME 
ORDER BY TOTAL_ORDER 
LIMIT 5;

-- 5. TOP PIZZA BY QUANTITY SOLD

SELECT PIZZA_NAME, SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM PIZZA_SALES
GROUP BY PIZZA_NAME 
ORDER BY TOTAL_QUANTITY_SOLD DESC
LIMIT 5;

-- 6. BOTTOM PIZZA BY QUANTITY SOLD

SELECT PIZZA_NAME, SUM(QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM PIZZA_SALES
GROUP BY PIZZA_NAME 
ORDER BY TOTAL_QUANTITY_SOLD 
LIMIT 5;